# Generated by Django 4.0.6 on 2022-11-08 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_facilitypage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='facilitypage',
            new_name='facility',
        ),
    ]
